### ISSUE TITLE
Breakages due to #1695

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#1710]
I'm running with the latest main code, and I think this is causing an error for me:
```shell
$ ./scorecard --repo=dart-lang/sdk --checks=Fuzzing
Starting [Fuzzing]
2022/03/03 19:26:00 internal error: ListCommits:error during graphqlHandler.setup: commit d3e36fab5eb55706a36144fe41abc2546ffa0b55: cannot retrieve committer login
panic: internal error: ListCommits:error during graphqlHandler.setup: commit d3e36fab5eb55706a36144fe41abc2546ffa0b55: cannot retrieve committer login

goroutine 1 [running]:
log.Panic({0xc000667ab8, 0xc0002be1c0, 0x100df38})
        log/log.go:354 +0x65
github.com/ossf/scorecard/v4/cmd.rootCmd(0xc000470000)
        github.com/ossf/scorecard/v4/cmd/root.go:138 +0x751
github.com/ossf/scorecard/v4/cmd.New.func2(0xc000421680, {0xe9e91a, 0x2, 0x2})
        github.com/ossf/scorecard/v4/cmd/root.go:62 +0x1d
github.com/spf13/cobra.(*Command).execute(0xc000421680, {0xc0000a8160, 0x2, 0x2})
        github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000421680)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        github.com/ossf/scorecard/v4/main.go:27 +0x25
```

_Originally posted by @chrismcgehee in https://github.com/ossf/scorecard/pull/1695#discussion_r819238713_

**Comment by naveensrinivasan** [comment]
We should add this as an e2e tests.

**Comment by laurentsimon** [comment]
Let me dig into this today. In the meantime, comment out those 3 lines if it's causing problems https://github.com/ossf/scorecard/blob/main/clients/githubrepo/graphql.go#L217-L219
