### ISSUE TITLE
Panic on scorecard execution

### ISSUE THREAD

**Issue by hazcod** [ossf/scorecard#642]
**Describe the bug**
A scorecard run triggers a sigsev panic.

**Reproduction steps**
```shell
~ % GO111MODULE=on go get github.com/ossf/scorecard
go: downloading github.com/ossf/scorecard v1.2.0
~ %  GITHUB_AUTH_TOKEN="xxx" scorecard --repo=github.com/ironpeakservices/ironpeak.be --show-details
Starting [Active]
Starting [Branch-Protection]
Starting [CI-Tests]
Starting [CII-Best-Practices]
Starting [Code-Review]
Starting [Contributors]
Starting [Frozen-Deps]
Starting [Fuzzing]
Starting [Packaging]
Starting [Pull-Requests]
Starting [SAST]
Starting [Security-Policy]
Starting [Signed-Releases]
Starting [Signed-Tags]
{"level":"info","ts":1625210973.621213,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.621191,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.621512,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.621561,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.6215549,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.621259,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.6216052,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.6212292,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.6214762,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.6212428,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.621637,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.6220958,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.621206,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625210973.622186,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
Finished [Signed-Releases]
Finished [Signed-Tags]
Finished [Fuzzing]
Finished [SAST]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1051573a0]

goroutine 24 [running]:
github.com/ossf/scorecard/checks.IsPrReviewRequired(0x1056c1c18, 0x140001a4000, 0x14000096000, 0x14000010010, 0x140000320c0, 0x140001d8313, 0x10, 0x140001d8324, 0xb, 0x14000074030, ...)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/checks/code_review.go:109 +0xf0
github.com/ossf/scorecard/checker.MultiCheck.func1(0x1056c1c18, 0x140001a4000, 0x14000096000, 0x14000010010, 0x140000320c0, 0x140001d8313, 0x10, 0x140001d8324, 0xb, 0x14000074030, ...)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/checker/check.go:64 +0xa0
github.com/ossf/scorecard/checks.DoesCodeReview(0x1056c1c18, 0x140001a4000, 0x14000096000, 0x14000010010, 0x140000320c0, 0x140001d8313, 0x10, 0x140001d8324, 0xb, 0x14000074030, ...)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/checks/code_review.go:39 +0xac
github.com/ossf/scorecard/checker.(*Runner).Run(0x1400047be40, 0x1056a0f28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/checker/checker.go:54 +0x148
github.com/ossf/scorecard/pkg.RunScorecards.func1(0x1056c1c18, 0x140001a4000, 0x140001bc498, 0x140001d8308, 0xa, 0x140001d8313, 0x10, 0x140001d8324, 0xb, 0x140001a5570, ...)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/pkg/scorecard.go:109 +0x1e0
created by github.com/ossf/scorecard/pkg.RunScorecards
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/pkg/scorecard.go:89 +0x11c
````

**Comment by naveensrinivasan** [comment]
Thanks, I can't seem to reproduce this on the main branch. Could you point it to the main branch and try it?

```
go run . --repo=github.com/ironpeakservices/ironpeak.be --show-details
go: downloading google.golang.org/api v0.49.0
go: downloading google.golang.org/genproto v0.0.0-20210624174822-c5cf32407d0a
go: downloading golang.org/x/sys v0.0.0-20210616094352-59db8d763f22
Starting [Frozen-Deps]
Starting [Token-Permissions]
Starting [Security-Policy]
Starting [Active]
Starting [Binary-Artifacts]
Starting [Branch-Protection]
Starting [Automatic-Dependency-Update]
Starting [Code-Review]
Starting [Packaging]
Starting [Signed-Releases]
Starting [Contributors]
Starting [Fuzzing]
Starting [SAST]
Starting [Signed-Tags]
Starting [Vulnerabilities]
Starting [CI-Tests]
Starting [CII-Best-Practices]
Starting [Pull-Requests]
Finished [CI-Tests]
Finished [CII-Best-Practices]
Finished [Pull-Requests]
Finished [Signed-Tags]
Finished [Vulnerabilities]
Finished [Security-Policy]
Finished [Active]
Finished [Binary-Artifacts]
Finished [Branch-Protection]
Finished [Frozen-Deps]
Finished [Token-Permissions]
Finished [Automatic-Dependency-Update]
Finished [Code-Review]
Finished [Packaging]
Finished [Contributors]
Finished [Fuzzing]
Finished [SAST]
Finished [Signed-Releases]

RESULTS
-------
Repo: github.com/ironpeakservices/ironpeak.be
Active: Pass 10
commits in last 90 days: 6
Automatic-Dependency-Update: Pass 10
dependabot config found: .github/dependabot.yml
Binary-Artifacts: Pass 10
Branch-Protection: Fail 0
error, retrying: unable to run check, retry: GET https://api.github.com/repos/ironpeakservices/ironpeak.be/branches/master/protection: 404 Not Found []
CI-Tests: Pass 10
CI test found: pr: 71, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/2562464947uccess
CI test found: pr: 70, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/2538423444uccess
CI test found: pr: 69, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/2047220198uccess
CI test found: pr: 68, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1869356465uccess
CI test found: pr: 67, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1742319108uccess
CI test found: pr: 66, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1742147063uccess
CI test found: pr: 65, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1394778193uccess
CI test found: pr: 64, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1241393060uccess
CI test found: pr: 63, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1229496144uccess
CI test found: pr: 62, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1220173749uccess
CI test found: pr: 61, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1219342719uccess
CI test found: pr: 60, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1219117155uccess
CI test found: pr: 59, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1213255406uccess
CI test found: pr: 58, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1213222539uccess
CI test found: pr: 57, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1213099910uccess
CI test found: pr: 56, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1211288432uccess
CI test found: pr: 55, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1208858344uccess
CI test found: pr: 54, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1208559902uccess
CI test found: pr: 53, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1101086179uccess
CI test found: pr: 52, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/1001734939uccess
CI test found: pr: 50, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/913099939uccess
CI test found: pr: 48, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/802497678uccess
CI test found: pr: 47, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/748852679uccess
CI test found: pr: 45, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/748846063uccess
CI test found: pr: 43, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/669829230uccess
CI test found: pr: 40, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/576318912uccess
CI test found: pr: 38, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/574524134uccess
CI test found: pr: 37, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/554345198uccess
CI test found: pr: 36, context: github-actionsuccess, url: https://api.github.com/repos/ironpeakservices/ironpeak.be/check-runs/515782510uccess
found CI tests for 29 of 29 merged PRs
CII-Best-Practices: Fail 10
no badge found
Code-Review: Pass 10
found pr with committer different than author: 35
found pr with committer different than author: 36
found pr with committer different than author: 37
found pr with committer different than author: 38
found pr with committer different than author: 40
found pr with committer different than author: 43
found pr with committer different than author: 45
found pr with committer different than author: 47
found pr with committer different than author: 48
found pr with committer different than author: 50
found pr with committer different than author: 52
found pr with committer different than author: 53
found pr with committer different than author: 54
found pr with committer different than author: 55
found pr with committer different than author: 56
found pr with committer different than author: 57
found pr with committer different than author: 58
found pr with committer different than author: 59
found pr with committer different than author: 60
found pr with committer different than author: 61
found pr with committer different than author: 62
found pr with committer different than author: 63
found pr with committer different than author: 64
found pr with committer different than author: 65
found pr with committer different than author: 66
found pr with committer different than author: 67
found pr with committer different than author: 68
found pr with committer different than author: 69
found pr with committer different than author: 70
found pr with committer different than author: 71
github code reviews found
Contributors: Fail 10
companies found: ironpeakservices
Frozen-Deps: Fail 10
!! frozen-deps/github-actions - .github/workflows/cloudflare.yaml has non-pinned dependency 'jakejarvis/cloudflare-purge-action@v0.3.0' (job 'Clear cloudflare cache')
!! frozen-deps/github-actions - .github/workflows/cloudflare.yaml has non-pinned dependency 'jakejarvis/cloudflare-purge-action@v0.3.0' (job 'Clear cloudflare cache')
!! frozen-deps/github-actions - .github/workflows/codeql-analysis.yml has non-pinned dependency 'actions/checkout@v2.3.4' (job 'Analyze')
!! frozen-deps/github-actions - .github/workflows/codeql-analysis.yml has non-pinned dependency 'github/codeql-action/init@v1' (job 'Analyze')
!! frozen-deps/github-actions - .github/workflows/codeql-analysis.yml has non-pinned dependency 'github/codeql-action/autobuild@v1' (job 'Analyze')
!! frozen-deps/github-actions - .github/workflows/codeql-analysis.yml has non-pinned dependency 'github/codeql-action/analyze@v1' (job 'Analyze')
!! frozen-deps/github-actions - .github/workflows/imgcmp.yaml has non-pinned dependency '9sako6/imgcmp@master' (job 'Optimize images')
!! frozen-deps/github-actions - .github/workflows/netlify.yaml has non-pinned dependency 'niklasmerz/github-deployment-action@v1.1.0' (job 'Cloudflare Pages')
!! frozen-deps/github-actions - .github/workflows/netlify.yaml has non-pinned dependency 'niklasmerz/github-deployment-action@v1.1.0' (job 'Cloudflare Pages')
!! frozen-deps/github-actions - .github/workflows/zap-daily.yaml has non-pinned dependency 'zaproxy/action-full-scan@v0.2.0' (job 'Scan public website')
!! frozen-deps/github-actions - .github/workflows/zap-daily.yaml has non-pinned dependency 'zaproxy/action-full-scan@v0.2.0' (job 'Scan k8s cluster')
Fuzzing: Fail 10
Packaging: Fail 10
!! not a packaging workflow: .github/workflows/cloudflare.yaml
!! not a packaging workflow: .github/workflows/codeql-analysis.yml
!! not a packaging workflow: .github/workflows/imgcmp.yaml
!! not a packaging workflow: .github/workflows/netlify.yaml
!! not a packaging workflow: .github/workflows/zap-daily.yaml
Pull-Requests: Fail 3
found commit with PR: 892d9f27a09ee8ce3a0c7052de32a5633434b83d
found commit with PR: 0eb8b08f5810c77f6b50412d68ea2d570e248e0c
!! found commit without PR: 4326814c4382c6ae890e0127b5479c2afcc24f6f, committer: web-flow
found commit with PR: ffb3d4ff52f7f8fc6ed529c53764e01c54561bcf
found commit with PR: aaa90fa318cf7d7db55f71d0ac8d39736f26aff7
found commit with PR: b12a78c17581f85b30a2e8f08c66f224e90b160d
found commit with PR: b20170bdc582e97a61e4387c2524dc86292df671
found commit with PR: 12973f9334ec01ef63d4a40d5bbf6eedbf533b04
found commit with PR: 6dfb330340115dc5f302c8de675dc53fac1a106e
!! found commit without PR: f5a2a82c44eaae24917a52d6b4de21fd9c2f1f3d, committer: hazcod
found commit with PR: 0d21f7b216e068e255dd3577b3632800f1eb65b4
found commit with PR: a505bb4661868917240f745fd979cbbe789fbff9
found commit with PR: 457435467d21849c3d9df236303a557588b3d38c
!! found commit without PR: 2e6d46c293c3b66bcfa2a9307a3ddff1dd2ea6b7, committer: web-flow
found commit with PR: 746f01c899329d096f16a21e67fbeead8078cb47
found commit with PR: 514bb2b58cc65919f9e72c36de1ee4503c9ac737
found commit with PR: ddaf3ad4dd6a9d51fd6a3b50f6c9ddf370b9bcf6
found commit with PR: 6ed59a66c557c87b770569c266e6ac501d24cad7
found commit with PR: c2cc2ab71ccf9de898ae657dbfbf1fc07da5034e
found commit with PR: 9d02661d3a23072e2a97c5c7ea7a3f67e611febc
found commit with PR: b2172d6fb2caeb50a7e6a0bef0ec5b30cd788816
found commit with PR: 6405434788364563f9d5e97757f8e434b032ddb3
found commit with PR: f221d7edf2f639b557856e73a17a2eab4e71a1b9
!! found commit without PR: c559664a432e64a31a1111797306416bfa344f1e, committer: web-flow
!! found commit without PR: f6e38b2a9b7281fb1a86c1e21319b6008fd2b2e6, committer: web-flow
!! found commit without PR: 605b5f26ee18ac247b74cd3fa613b6b82c8a8b67, committer: web-flow
!! found commit without PR: faffc4e43bb3b31da6f49ce9a18a52cdd2a98578, committer: web-flow
!! found commit without PR: d753bd952bdc7204aecc359bd4c32d7a7e86447f, committer: web-flow
!! found commit without PR: fe6157ad1bef0b60a3dc73e29ad5ee3a35b4c39c, committer: web-flow
found commit with PR: 5d33a03773f8d6479b6d753f0c19188f57c15b52
found PRs for 21 out of 30 commits
SAST: Pass 10
found CodeQL definition: .github/workflows/codeql-analysis.yml
Security-Policy: Fail 5
Signed-Releases: Fail 0
no releases found
Signed-Tags: Fail 0
no tags found
Token-Permissions: Fail 10
!! token-permissions/github-token - no permission defined in .github/workflows/cloudflare.yaml
!! token-permissions/github-token - no permission defined in .github/workflows/codeql-analysis.yml
!! token-permissions/github-token - no permission defined in .github/workflows/imgcmp.yaml
!! token-permissions/github-token - no permission defined in .github/workflows/netlify.yaml
!! token-permissions/github-token - no permission defined in .github/workflows/zap-daily.yaml
Vulnerabilities: Pass 10
```

**Comment by azeemshaikh38** [comment]
+1. I can't seem to reproduce this either. I ran:

```
$go version
go version go1.16.5 linux/amd64
$GO111MODULE=on go get github.com/ossf/scorecard
$GITHUB_AUTH_TOKEN="xyz" scorecard --repo=github.com/ironpeakservices/ironpeak.be --show-details
```

**Comment by azeemshaikh38** [comment]
Closing the issue. Please re-open if you were able to reproduce the problem or the problem persists.

**Comment by hazcod** [comment]
Hmm, it's still happening. This is on a macOS M1 system btw.

```shell
niels@hyde scorecard %  GITHUB_AUTH_TOKEN="xxx" ~/Source/go/bin/scorecard --repo=github.com/ironpeakservices/ironpeak.be --show-details       
Starting [Active]
Starting [Branch-Protection]
Starting [CI-Tests]
Starting [CII-Best-Practices]
Starting [Code-Review]
Starting [Contributors]
Starting [Frozen-Deps]
Starting [Fuzzing]
Starting [Packaging]
Starting [Pull-Requests]
Starting [SAST]
Starting [Security-Policy]
Starting [Signed-Releases]
Starting [Signed-Tags]
{"level":"info","ts":1625671417.608052,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.6078641,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.608105,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.608143,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.607865,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.608286,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.608313,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.6084611,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.608465,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.608476,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.608481,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.608628,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.609484,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
{"level":"info","ts":1625671417.6095731,"caller":"roundtripper/roundtripper.go:65","msg":"using token 0 of total 1."}
Finished [Signed-Releases]
Finished [Signed-Tags]
Finished [Fuzzing]
Finished [SAST]
Finished [Branch-Protection]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1052773a0]

goroutine 24 [running]:
github.com/ossf/scorecard/checks.IsPrReviewRequired(0x1057e1c18, 0x1400019c000, 0x14000096580, 0x14000010040, 0x14000032360, 0x140001b4343, 0x10, 0x140001b4354, 0xb, 0x140000740f0, ...)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/checks/code_review.go:109 +0xf0
github.com/ossf/scorecard/checker.MultiCheck.func1(0x1057e1c18, 0x1400019c000, 0x14000096580, 0x14000010040, 0x14000032360, 0x140001b4343, 0x10, 0x140001b4354, 0xb, 0x140000740f0, ...)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/checker/check.go:64 +0xa0
github.com/ossf/scorecard/checks.DoesCodeReview(0x1057e1c18, 0x1400019c000, 0x14000096580, 0x14000010040, 0x14000032360, 0x140001b4343, 0x10, 0x140001b4354, 0xb, 0x140000740f0, ...)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/checks/code_review.go:39 +0xac
github.com/ossf/scorecard/checker.(*Runner).Run(0x14000353e40, 0x1057c0f28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/checker/checker.go:54 +0x148
github.com/ossf/scorecard/pkg.RunScorecards.func1(0x1057e1c18, 0x1400019c000, 0x140001b6498, 0x140001b4338, 0xa, 0x140001b4343, 0x10, 0x140001b4354, 0xb, 0x1400019d570, ...)
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/pkg/scorecard.go:109 +0x1e0
created by github.com/ossf/scorecard/pkg.RunScorecards
	/Users/niels/Source/go/pkg/mod/github.com/ossf/scorecard@v1.2.0/pkg/scorecard.go:89 +0x11c
niels@hyde scorecard % go version
go version go1.16.5 darwin/arm64
```

**Comment by naveensrinivasan** [comment]
Interesting! Probably should include in running on `osx` as part of the tests. The actions does not support `m1` https://github.com/actions/virtual-environments/issues/2187

**Comment by naveensrinivasan** [comment]
Is this happening for every repository?

**Comment by hazcod** [comment]
Does not happen for `github.com/ossf/scorecard` 🤔

**Comment by rnjudge** [comment]
FWIW, I am also seeing this issue for the `github.com/tern-tools/tern` repository and I have seen it multiple times:

```
$ ./scorecard --repo=github.com/tern-tools/tern
Starting [CI-Tests]
Starting [Fuzzing]
Starting [Active]
Starting [Automatic-Dependency-Update]
Starting [CII-Best-Practices]
Starting [Token-Permissions]
Starting [Pull-Requests]
Starting [SAST]
Starting [Security-Policy]
Starting [Branch-Protection]
Starting [Code-Review]
Starting [Contributors]
Starting [Frozen-Deps]
Starting [Signed-Releases]
Starting [Signed-Tags]
Starting [Binary-Artifacts]
Starting [Packaging]
Starting [Vulnerabilities]
{"level":"warn","ts":1626114096.3972945,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 22m28.602729221s to retry..."}

```

```
Starting [Pull-Requests]
{"level":"warn","ts":1626108247.218526,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m59.781488331s to retry..."}
{"level":"warn","ts":1626108247.2402127,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m59.759794276s to retry..."}
{"level":"warn","ts":1626108249.4006603,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m55.599375103s to retry..."}
{"level":"warn","ts":1626108249.4019876,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m55.598019001s to retry..."}
{"level":"warn","ts":1626108249.418286,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m55.581724948s to retry..."}
{"level":"warn","ts":1626108249.4588823,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m55.541129001s to retry..."}
{"level":"warn","ts":1626108249.4828103,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m55.51719988s to retry..."}
{"level":"warn","ts":1626111845.0002537,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.0008707,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.0022173,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.002294,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.0023384,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.151078,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting -151.068814ms to retry..."}
{"level":"warn","ts":1626111845.1513531,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.1512365,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting -151.233529ms to retry..."}
{"level":"warn","ts":1626111845.1516898,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.1520026,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting -151.999506ms to retry..."}
{"level":"warn","ts":1626111845.1521258,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.1526062,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting -152.602996ms to retry..."}
{"level":"warn","ts":1626111845.152767,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.1530135,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting -153.010675ms to retry..."}
{"level":"warn","ts":1626111845.1531382,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.175641,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting -175.633024ms to retry..."}
{"level":"warn","ts":1626111845.1760185,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111845.1759393,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting -175.93623ms to retry..."}
{"level":"warn","ts":1626111845.1763117,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111847.0007164,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111847.0013008,"caller":"roundtripper/rate_limit.go:62","msg":"Rate limit exceeded. Retrying..."}
{"level":"warn","ts":1626111847.190758,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m59.809286457s to retry..."}
{"level":"warn","ts":1626111847.7060697,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m56.293938841s to retry..."}
{"level":"warn","ts":1626111847.8431315,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m56.156876887s to retry..."}
{"level":"warn","ts":1626111847.891055,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m56.10895263s to retry..."}
{"level":"warn","ts":1626111847.9266534,"caller":"roundtripper/rate_limit.go:58","msg":"Rate limit exceeded. Waiting 59m56.073354821s to retry..."}
```

**Comment by azeemshaikh38** [comment]
Assigning this to myself. I still haven't been able to reproduce this (even on MacOS). Will try to get some virtual Mac machine with ARM architecture and see if I can reproduce this issue. I have a hunch that this is coming from https://github.com/ossf/scorecard/blob/main/checks/code_review.go#L142, where `BranchProtectionRule` is `null`. Although I want to root cause this and figure out what environment causes this bug.

**Comment by naveensrinivasan** [comment]
We have an ARM release https://github.com/ossf/scorecard/releases/tag/v2.1.3, could you please try this and let us know?
